Update repository to PureScript 0.15.4 (#292)
* Update purescript and parcel

* Add parcel and package-lock to .gitignore

* Broken concur receipes

* Broken Payload (not updated yet)

* Fix affjax, css

* Fix RunCapabilityPatternNode

* Fix ShapesHalogenHooks

* Fix SignalSnakeJs

* Fix SignalTrisJs

* Fix SimpleASTParserLog

* Run ButtonsReactHooks

* Update all index.html with type module

* Update all index.js imports

* build-web: no-optimize option

* Remove unused psci-support

* Drop unused dependencies, remove warnings

* Fix for CI failing without esbuild

> Error:  Failed to find esbuild.

* Review changes: args, process, imports

* Dropping named unused args
* Dropping process dependency
* Deleting more unused imports (warnings)

* Update README

* Add process dependency

SignalRenderJs requires the dependency. Will be added by parcel
otherwise.

* package-set 0.15.3-20220712

* Make README: try.purescript.org, '/' in github arg

* Temporarily remove try link